import Layout from '../Layouts/Layout';
import './globals.css';

import { gsap } from 'gsap/dist/gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { ScrollToPlugin } from 'gsap/dist/ScrollToPlugin';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
